import { StyleSheet } from 'react-native';
import { colors, borderRadius } from '../../../shared/design/theme';
import { typography } from '../../../shared/design/typography';
import { spacing } from '../../../shared/design/spacing';
import type { ViewStyle, TextStyle } from 'react-native';

const styles = StyleSheet.create({
  addBoulderButton: {
    alignItems: 'center' as ViewStyle['alignItems'],
    backgroundColor: colors.primary,
    borderRadius: borderRadius.lg,
    marginBottom: spacing.sm,
    paddingVertical: spacing.md,
  },
  addBoulderText: {
    ...typography.button,
    color: colors.textOnPrimary,
  },
  boulderRow: {
    alignItems: 'center' as ViewStyle['alignItems'],
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: borderRadius.sm,
    borderWidth: 1,
    flexDirection: 'row' as ViewStyle['flexDirection'],
    marginBottom: spacing.xs,
    padding: spacing.sm,
  },
  boulderText: {
    ...typography.bodyBold,
    color: colors.primary,
    marginRight: spacing.sm,
  },
  bouldersContainer: {
    flexDirection: 'row' as ViewStyle['flexDirection'],
    flexWrap: 'wrap' as ViewStyle['flexWrap'],
    justifyContent: 'flex-start' as ViewStyle['justifyContent'],
    marginTop: spacing.xs,
  },
  button: {
    alignItems: 'center' as ViewStyle['alignItems'],
    backgroundColor: colors.surface,
    borderColor: colors.primary,
    borderRadius: borderRadius.full,
    borderWidth: 1,
    elevation: 2,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  buttonPrimary: {
    alignItems: 'center' as ViewStyle['alignItems'],
    backgroundColor: colors.primary,
    borderRadius: borderRadius.full,
    elevation: 2,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  buttonText: {
    ...typography.button,
    color: colors.primary,
  },
  buttonTextPrimary: {
    ...typography.button,
    color: colors.textOnPrimary,
  },
  chip: {
    backgroundColor: colors.surface,
    borderColor: colors.primary,
    borderRadius: borderRadius.lg,
    borderWidth: 1,
    marginRight: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  chipSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  container: {
    flex: 1,
    padding: spacing.md,
    backgroundColor: colors.background,
  } as ViewStyle,
  durationInput: {
    ...typography.body,
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    marginBottom: spacing.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  emptyLoggedText: {
    ...typography.bodySmall,
    color: colors.textSecondary,
    marginBottom: spacing.sm,
  },
  emptyText: {
    ...typography.bodySmall,
    color: colors.textSecondary,
    marginVertical: spacing.sm,
  },
  errorText: {
    ...typography.caption,
    color: colors.error,
    marginBottom: spacing.sm,
    marginTop: -spacing.xs,
  },
  input: {
    ...typography.body,
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: borderRadius.md,
    padding: spacing.sm,
    backgroundColor: colors.surface,
    color: colors.text,
    marginBottom: spacing.sm,
  } as TextStyle,
  label: {
    ...typography.bodyBold,
    color: colors.primary,
    marginBottom: spacing.xs,
    marginTop: spacing.sm,
  },
  loggedBouldersLabel: {
    ...typography.captionBold,
    color: colors.text,
    marginBottom: spacing.xs,
    marginTop: spacing.md,
  },
  manageSystemsButton: {
    alignSelf: 'flex-start' as ViewStyle['alignSelf'],
    marginBottom: spacing.sm,
  },
  manageSystemsText: {
    ...typography.captionBold,
    color: colors.primary,
  },
  modalContent: {
    backgroundColor: colors.surface,
    borderRadius: borderRadius.md,
    elevation: 4,
    maxWidth: 400,
    padding: spacing.lg,
    width: '90%',
  },
  modalOverlay: {
    alignItems: 'center' as ViewStyle['alignItems'],
    backgroundColor: colors.overlay,
    flex: 1,
    justifyContent: 'center' as ViewStyle['justifyContent'],
  },
  notesInput: {
    ...typography.bodySmall,
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    height: 80,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    textAlignVertical: 'top' as TextStyle['textAlignVertical'],
  },
  notesLabel: {
    ...typography.captionBold,
    color: colors.text,
    marginBottom: spacing.xs,
    marginTop: spacing.md,
  },
  saveButton: {
    alignItems: 'center' as ViewStyle['alignItems'],
    backgroundColor: colors.primary,
    borderRadius: borderRadius.lg,
    marginBottom: spacing.sm,
    marginTop: spacing.xl,
    paddingVertical: spacing.md,
  },
  saveButtonDisabled: {
    opacity: 0.7,
  },
  saveButtonText: {
    ...typography.buttonLarge,
    color: colors.textOnPrimary,
  },
  screenContainer: {
    backgroundColor: colors.background,
    flex: 1,
  },
  scrollContainer: {
    flexGrow: 1,
    paddingBottom: spacing.xl,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
  },
  sectionLabel: {
    ...typography.captionBold,
    color: colors.text,
    marginBottom: spacing.xs,
  },
});

export default styles;
