import { StyleSheet } from 'react-native';
import { colors } from '../../../shared/theme';
import type { ViewStyle, TextStyle } from 'react-native';

const styles = StyleSheet.create({
  addBoulderButton: {
    alignItems: 'center' as ViewStyle['alignItems'],
    backgroundColor: '#2563EB',
    borderRadius: 14,
    marginBottom: 12,
    paddingVertical: 14,
  },
  addBoulderText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600' as TextStyle['fontWeight'],
  },
  boulderRow: {
    alignItems: 'center' as ViewStyle['alignItems'],
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 6,
    borderWidth: 1,
    flexDirection: 'row' as ViewStyle['flexDirection'],
    marginBottom: 6,
    padding: 8,
  },
  boulderText: {
    color: colors.primary,
    fontWeight: '700' as TextStyle['fontWeight'],
    marginRight: 12,
  },
  bouldersContainer: {
    flexDirection: 'row' as ViewStyle['flexDirection'],
    flexWrap: 'wrap' as ViewStyle['flexWrap'],
    justifyContent: 'flex-start' as ViewStyle['justifyContent'],
    marginTop: 4,
  },
  button: {
    alignItems: 'center' as ViewStyle['alignItems'],
    backgroundColor: colors.surface,
    borderColor: colors.primary,
    borderRadius: 24,
    borderWidth: 1,
    elevation: 2,
    paddingHorizontal: 24,
    paddingVertical: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  buttonPrimary: {
    alignItems: 'center' as ViewStyle['alignItems'],
    backgroundColor: colors.primary,
    borderRadius: 24,
    elevation: 2,
    paddingHorizontal: 24,
    paddingVertical: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  buttonText: {
    color: colors.primary,
    fontSize: 16,
    fontWeight: '700' as TextStyle['fontWeight'],
  },
  buttonTextPrimary: {
    color: colors.surface,
    fontSize: 16,
    fontWeight: '700' as TextStyle['fontWeight'],
  },
  chip: {
    backgroundColor: colors.surface,
    borderColor: colors.primary,
    borderRadius: 16,
    borderWidth: 1,
    marginRight: 8,
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  chipSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  container: {
    flex: 1,
    padding: 16,
    backgroundColor: colors.background,
  } as ViewStyle,
  durationInput: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E2E8F0',
    borderRadius: 12,
    borderWidth: 1,
    fontSize: 16,
    marginBottom: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  emptyLoggedText: {
    color: '#64748B',
    marginBottom: 8,
  },
  emptyText: {
    color: '#888',
    marginVertical: 8,
  },
  errorText: {
    color: colors.error,
    fontSize: 12,
    marginBottom: 12,
    marginTop: -4,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: 12,
    padding: 10,
    backgroundColor: colors.surface,
    color: colors.text,
    marginBottom: 8,
  } as TextStyle,
  label: {
    color: colors.primary,
    fontWeight: '700' as TextStyle['fontWeight'],
    marginBottom: 4,
    marginTop: 12,
  },
  loggedBouldersLabel: {
    color: '#0F172A',
    fontWeight: '600' as TextStyle['fontWeight'],
    marginBottom: 4,
    marginTop: 16,
  },
  manageSystemsButton: {
    alignSelf: 'flex-start' as ViewStyle['alignSelf'],
    marginBottom: 8,
  },
  manageSystemsText: {
    color: colors.primary,
    fontWeight: '600' as TextStyle['fontWeight'],
  },
  modalContent: {
    backgroundColor: colors.surface,
    borderRadius: 10,
    elevation: 4,
    maxWidth: 400,
    padding: 20,
    width: '90%',
  },
  modalOverlay: {
    alignItems: 'center' as ViewStyle['alignItems'],
    backgroundColor: 'rgba(0,0,0,0.3)',
    flex: 1,
    justifyContent: 'center' as ViewStyle['justifyContent'],
  },
  notesInput: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E2E8F0',
    borderRadius: 12,
    borderWidth: 1,
    fontSize: 15,
    height: 80,
    paddingHorizontal: 14,
    paddingVertical: 12,
    textAlignVertical: 'top' as TextStyle['textAlignVertical'],
  },
  notesLabel: {
    color: '#0F172A',
    fontWeight: '600' as TextStyle['fontWeight'],
    marginBottom: 4,
    marginTop: 16,
  },
  saveButton: {
    alignItems: 'center' as ViewStyle['alignItems'],
    backgroundColor: '#0F172A',
    borderRadius: 16,
    marginBottom: 12,
    marginTop: 28,
    paddingVertical: 16,
  },
  saveButtonDisabled: {
    opacity: 0.7,
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700' as TextStyle['fontWeight'],
  },
  screenContainer: {
    backgroundColor: '#F1F5F9',
    flex: 1,
  },
  scrollContainer: {
    flexGrow: 1,
    paddingBottom: 32,
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  sectionLabel: {
    color: '#0F172A',
    fontWeight: '600' as TextStyle['fontWeight'],
    marginBottom: 4,
  },
});

export default styles;
